### ISSUE TITLE
Download vuln DB not considering private registry options

### ISSUE THREAD

**Issue by 24mu13** [georg-jung/trivy-azure-pipelines-task#4]
Congrats for the good work with this contrib version of the task!
BTW I think make sense to do a rebase on upstream since they implemented few things recently.

The retry mechanism you implemented (https://github.com/georg-jung/trivy-azure-pipelines-task/commit/d87c31041b1e32ae7e45311e5177cf9d7b4bd593) does not consider the following options: db-repository, java-db-repository, checks-bundle-repository.

The only effective way as for now to workaround the https://github.com/aquasecurity/trivy-azure-pipelines-task/issues/82 in fact is using  **public.ecr.aws** as registry. This is working well, apart for the **downloadVulnDb** that could still fail for TOOMANYREQUESTS.

```yaml
parameters:
  - name: privateRegistry
    type: string
    # see: https://github.com/aquasecurity/trivy/discussions/7538
    default: public.ecr.aws

steps:
  - task: trivy-contrib@1
    inputs:
      image: ${{ parameters.repositoryPrefix }}${{ imageName }}
      scanners: vuln
      ignoreUnfixed: true
      options: >
        --db-repository ${{ parameters.privateRegistry }}/aquasecurity/trivy-db
        --java-db-repository ${{ parameters.privateRegistry }}/aquasecurity/trivy-java-db 
        --checks-bundle-repository ${{ parameters.privateRegistry }}/aquasecurity/trivy-checks 
```
